build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:trixie"
  amd64:   "ghcr.io/home-assistant/amd64-base-debian:trixie"
labels:
  org.opencontainers.image.title: "Home Assistant App: eBUSd"
  org.opencontainers.image.description: "Transparent wrapper of john30/ebusd — a daemon for communicating with eBUS devices (heating systems)"
  org.opencontainers.image.source: "https://github.com/LukasGrebe/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
