build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
  armhf: "ghcr.io/home-assistant/armhf-base:3.18"
  armv7: "ghcr.io/home-assistant/armv7-base:3.18"
  i386: "ghcr.io/home-assistant/i386-base:3.18"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Ebusd"
  org.opencontainers.image.description: "This Add-on runs eBUSd, a daemon for handling communication with eBUS devices"
  org.opencontainers.image.source: "https://github.com/LukasGrebe/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
