name: Feature request
description: Suggest an improvement to the eBUSd add-on
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Workarounds or alternatives you've tried
    validations:
      required: false
