name: Build and Test Add-on

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: ["ebusd"]
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.2.2

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: ./${{ matrix.addon }}

      - name: Build ${{ matrix.arch }} add-on
        if: contains(steps.info.outputs.architectures, matrix.arch)
        uses: home-assistant/builder@2024.08.2
        with:
          args: |
            --${{ matrix.arch }} \
            --target ${{matrix.addon}} \
            --image "ha-addon-ebusd-${{ matrix.arch }}" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --test
